CC=g++
FLAG=-g
FLAG+= -std=gnu++11
TARGET= lambada
OBJECTS= *.o 
all: $(TARGET)
$(TARGET): $(OBJECTS)
	$(CC) -c *.cpp
.PHONY: clean
clean:
	rm -f oops *.o *.gch
	
#1_simpleVectorElementProcess.cpp
#2_DoingSamleOpertionUsingFunction.cpp
#3_replaceFunctionWith_lambda_function.cpp
#4_Yes_we_can_give_name_lembda_fun.cpp
#5_lembada_usingCaptureClause.cpp
