#include <iostream>

/*The name of the namespace is uniquely generated by the compiler.
the unnamed namespace is assiable inside only within file 
*/
namespace {
	int testUnnamed =66;
}
int main(){
	std::cout<<testUnnamed<<std::endl;
	return 0;
}